apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: jx-cluster
    devEnvApprovers:
    - bussrrajeshnayak
    environmentGitOwner: bussrrajeshnayak
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "339306295059"
    kanikoFlags: --skip-unused-stages --snapshotMode=redo
    project: devops-saas
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - key: dev
    owner: bussrrajeshnayak
    repository: jx3-gke-gsm
  - key: staging
  - key: production
  ingress:
    domain: 35.238.48.250.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kuberhealthy: true
  pipelineUser:
    username: bussrrajeshnayak
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-jx-cluster-7a89153b7e04
  - name: reports
    url: gs://reports-jx-cluster-7a89153b7e04
  - name: repository
    url: gs://repository-jx-cluster-7a89153b7e04
  vault: {}
  webhook: lighthouse
